/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appatencionemergencia;

import appatencionemargencia.upn.proyectofinal.DAO.TipoTrabajadorDAO;
import appatencionemargencia.upn.proyectofinal.DAO.TrabajadorDAO;
import appatencionemergencia.upn.proyectofinal.Entidades.Tipo_Trabajador;
import appatencionemergencia.upn.proyectofinal.Entidades.Trabajador;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paul
 */


public class Administrador_Trabajador extends javax.swing.JInternalFrame {

    /**
     * Creates new form Administrador_Trabajador
     */
    public List<Tipo_Trabajador> listartipo;
    public List<Trabajador> listarTrabajador;
    Tipo_Trabajador tipoTrab;
    Trabajador objTrabajador;
    
    public Administrador_Trabajador() {
        initComponents();
        CargarTipoTrabajador();
        ListarTrabajadores();
    }

    void CargarTipoTrabajador(){
        try {
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            listartipo =  new TipoTrabajadorDAO().ListaDeTipo();
            for (Tipo_Trabajador tipo : listartipo) {
                model.addElement(tipo.getDescripcion());
            }
            cboTipo.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de base de datos" + e.getMessage());
            System.out.println("Error: Carga Tipo de Trabajador");
        }
    }
    
    void ListarTrabajadores(){
        try {
            TrabajadorDAO dao = new TrabajadorDAO();
            listarTrabajador = dao.ListarTrabajador();
            DefaultTableModel modelo1 = new DefaultTableModel();
            
            modelo1.addColumn("Nombre");
            modelo1.addColumn("Apellido Paterno");
            modelo1.addColumn("Apellido Materno");
            modelo1.addColumn("Tipo Trabajador");
      
            for (Trabajador trabajador : listarTrabajador) {
                modelo1.addRow(new String[]{
                    trabajador.getNombre()+"",
                    trabajador.getApellidoPaterno()+"",
                    trabajador.getApellidoMaterno()+"",
                    trabajador.getObjTipoTrabajador().getDescripcion()+"",
                });
            }
            tblListaTrabajadores.setModel(modelo1);
        } catch (Exception e) {
            System.out.println("error --> interfaz --> trabajador --> listar");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaTrabajadores = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApePa = new javax.swing.JTextField();
        txtApeMa = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();
        cboTipo = new javax.swing.JComboBox();
        btnGuardar = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Trabajadores"));

        tblListaTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblListaTrabajadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaTrabajadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListaTrabajadores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Trabajador"));

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Apellido Paterno");

        jLabel3.setText("Apellido Materno");

        jLabel4.setText("N° de Colegiatura :");

        jLabel5.setText("Telefono: ");

        jLabel6.setText("Usuario : ");

        jLabel7.setText("Clave : ");

        jLabel8.setText("Tipo de Trabajador: ");

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre)
                    .addComponent(txtApePa)
                    .addComponent(txtApeMa)
                    .addComponent(txtNumero)
                    .addComponent(txtTelefono)
                    .addComponent(txtUsuario)
                    .addComponent(txtClave)
                    .addComponent(cboTipo, 0, 136, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApePa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApeMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        BtnActualizar.setText("Actualizar");
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnGuardar)
                        .addGap(39, 39, 39)
                        .addComponent(BtnActualizar)
                        .addGap(31, 31, 31)
                        .addComponent(btnEliminar)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar)
                            .addComponent(BtnActualizar)
                            .addComponent(btnEliminar))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            Trabajador objTraba = new Trabajador();
            TrabajadorDAO dao = new TrabajadorDAO();
            int posicionSeleccionada = cboTipo.getSelectedIndex();
            Tipo_Trabajador objTipoSeleccionada = listartipo.get(posicionSeleccionada);
            objTraba.setNombre(txtNombre.getText());
            objTraba.setApellidoPaterno(txtApePa.getText());
            objTraba.setApellidoMaterno(txtApeMa.getText());
            objTraba.setNroColegiatura(txtNumero.getText());
            objTraba.setTelefono(txtTelefono.getText());
            objTraba.setUsuario(txtUsuario.getText());
            objTraba.setClave(txtClave.getText());
            objTraba.setObjTipoTrabajador(objTipoSeleccionada);
            if (dao.RegistrarTrabajador(objTraba)) {
                  JOptionPane.showMessageDialog(this, "Se registro correctamente al Trabajador ");
                  ListarTrabajadores();
            }else{
                JOptionPane.showMessageDialog(this, "No se registro correctamente al Trabajador ");
            }
        } catch (Exception e) {
            System.out.println("error --> interfaz --> trabajador --> Guardar");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblListaTrabajadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaTrabajadoresMouseClicked
        // TODO add your handling code here:
        int fila = tblListaTrabajadores.getSelectedRow();
        if (fila !=-1) {
            objTrabajador = listarTrabajador.get(fila);
            tipoTrab = objTrabajador.getObjTipoTrabajador();
            
            txtNombre.setText(objTrabajador.getNombre());
            txtApePa.setText(objTrabajador.getApellidoPaterno());
            txtApeMa.setText(objTrabajador.getApellidoMaterno());
            txtNumero.setText(objTrabajador.getNroColegiatura());
            txtTelefono.setText(objTrabajador.getTelefono());
            txtUsuario.setText(objTrabajador.getUsuario());
            txtClave.setText(objTrabajador.getClave());
            cboTipo.setSelectedItem(String.valueOf(objTrabajador.getObjTipoTrabajador().getDescripcion()));
        }
    }//GEN-LAST:event_tblListaTrabajadoresMouseClicked

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        // TODO add your handling code here:
        try {
            TrabajadorDAO dao = new TrabajadorDAO();
            Trabajador obtTrabajador = new Trabajador();
            
            obtTrabajador.setNombre(txtNombre.getText());
            obtTrabajador.setApellidoPaterno(txtApePa.getText());
            obtTrabajador.setApellidoMaterno(txtApeMa.getText());
            obtTrabajador.setNroColegiatura(txtNumero.getText());
            obtTrabajador.setTelefono(txtTelefono.getText());
            obtTrabajador.setUsuario(txtUsuario.getText());
            obtTrabajador.setClave(txtClave.getText());
            obtTrabajador.setObjTipoTrabajador(listartipo.get(cboTipo.getSelectedIndex()));
            obtTrabajador.setId(objTrabajador.getId());
            if (dao.ActualizarTrabajador(obtTrabajador)) {
                JOptionPane.showMessageDialog(this, "Se Actualizo correctamente los datos del Trabajador ");
                ListarTrabajadores();
            }else{
                JOptionPane.showMessageDialog(this, "No lo pudimos actualizar por problemas internos ");
            }
        } catch (Exception e) {
            System.out.println(" ERROR --> Interfaz --> Trabajadro --> Actualizar --> " + e.getMessage());
        }
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        try {
            TrabajadorDAO dao =  new TrabajadorDAO();
            Trabajador trabajador = new Trabajador();
            
            trabajador.setId(objTrabajador.getId());
            
            if (dao.EliminarTrabajador(trabajador)) {
                JOptionPane.showMessageDialog(this, "Se Elimino correctamente");
                ListarTrabajadores();
            }else{
                JOptionPane.showMessageDialog(this, "No se Elimino correctamente");
            }
        } catch (Exception e) {
             System.out.println(" ERROR --> INTERFAZ --> TRABAJADOR --> Eliminar --> " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaTrabajadores;
    private javax.swing.JTextField txtApeMa;
    private javax.swing.JTextField txtApePa;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
